# Generated by Django 4.1.3 on 2022-12-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profilepage", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
