# Generated by Django 4.1 on 2022-12-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_customer', '0006_alter_review_customer_alter_review_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
